#!/usr/bin/env zsh
# .app bundle generator for Claude Desktop multi-instance wrappers.
#
# Public entry point: _ckipper_desktop_bundle_write. Produces a minimal,
# fully-formed macOS .app bundle (Info.plist + launcher + optional icon)
# whose launcher exec's `open -n -a /Applications/Claude.app` with the
# instance's --user-data-dir baked in at generation time.
#
# Test seams: _CKIPPER_TEST_CLAUDE_APP overrides the system Claude.app path
# used for icon copying; _CKIPPER_TEST_LSREGISTER overrides the lsregister
# binary path. Both are read inside helper bodies (NOT at module load) so
# per-test exports take effect.

# Full system path to lsregister — not on $PATH, so we invoke it absolutely.
_CKIPPER_DESKTOP_LSREGISTER_PATH=/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister

# Canonical install path for Claude Desktop on macOS. Source of the icon and
# the executable our launcher exec's via `open -n -a`.
_CKIPPER_DESKTOP_SYSTEM_APP=/Applications/Claude.app

# Reverse-DNS prefix for wrapper bundle identifiers. The instance name is
# appended (e.g. work → dev.ckipper.claude.desktop.work).
_CKIPPER_DESKTOP_BUNDLE_ID_PREFIX=dev.ckipper.claude.desktop

# Mode bits for the generated launcher script (rwxr-xr-x).
_CKIPPER_DESKTOP_LAUNCHER_MODE=755

# Generate a complete .app bundle for a Claude Desktop instance.
#
# Materializes <bundle_path> with Contents/Info.plist, Contents/MacOS/launcher
# (chmod 755), and optionally Contents/Resources/AppIcon.icns (copied from the
# system Claude.app when present). Best-effort registers the new bundle with
# Launch Services via lsregister.
#
# Args:
#   $1 — instance name (lowercase canonical, e.g. "work" or "foo-bar")
#   $2 — absolute bundle path (e.g. ~/Applications/Claude-Work.app)
#   $3 — absolute user-data-dir path baked into the launcher's --user-data-dir
#
# Returns: 0 on success; non-zero if the bundle could not be written.
_ckipper_desktop_bundle_write() {
    local name="$1" bundle="$2" data_dir="$3"
    mkdir -p "$bundle/Contents/MacOS" "$bundle/Contents/Resources" || return 1
    _ckipper_desktop_bundle_write_launcher "$bundle" "$data_dir" || return 1
    local icon_copied=false
    if _ckipper_desktop_bundle_copy_icon "$bundle"; then
        icon_copied=true
    fi
    _ckipper_desktop_bundle_write_plist "$bundle" "$name" "$icon_copied" || return 1
    _ckipper_desktop_bundle_lsregister "$bundle"
    return 0
}

# Title-case a hyphen-segmented lowercase name.
#
# Splits on `-`, applies zsh's ${(C)…} case-transform to each segment
# (capitalizing the first letter), then rejoins with `-`. So "foo-bar"
# becomes "Foo-Bar" and "work" becomes "Work".
#
# Args: $1 — lowercase name (e.g. "foo-bar").
# Returns: 0 always. Prints the title-cased form on stdout.
_ckipper_desktop_bundle_title_case() {
    local name="$1"
    local -a segments titled
    segments=("${(@s:-:)name}")
    local seg
    for seg in "${segments[@]}"; do
        titled+=("${(C)seg}")
    done
    print -r -- "${(j:-:)titled}"
}

# Write the bundle's launcher script.
#
# The script exec's `open -n -a "<SYSTEM_APP>" --args
# --user-data-dir="<data_dir>"`, with the data_dir literal baked in at
# generation time (NOT resolved at runtime via path-walking).
#
# Args:
#   $1 — bundle path
#   $2 — user-data-dir to bake into --user-data-dir
#
# Returns: 0 on success; non-zero if the file could not be written/chmodded.
_ckipper_desktop_bundle_write_launcher() {
    local bundle="$1" data_dir="$2"
    local launcher="$bundle/Contents/MacOS/launcher"
    cat > "$launcher" <<EOF
#!/bin/zsh
# Auto-generated by ckipper desktop. Do not edit by hand — regenerate via
# \`ckipper desktop add\` / \`ckipper desktop rename\`.
exec open -n -a "$_CKIPPER_DESKTOP_SYSTEM_APP" --args --user-data-dir="$data_dir"
EOF
    chmod "$_CKIPPER_DESKTOP_LAUNCHER_MODE" "$launcher"
}

# Write Contents/Info.plist with the standard CFBundle keys.
#
# CFBundleIconFile is included ONLY when the caller signals an icon was
# copied — otherwise macOS would render a broken-icon glyph. CFBundleName
# is derived inside this function via _title_case so the orchestrator
# stays at the 3-parameter cap.
#
# Args:
#   $1 — bundle path
#   $2 — canonical lowercase name (for CFBundleIdentifier suffix + display)
#   $3 — "true" if an icon was copied; "false" otherwise
#
# Returns: 0 on success; non-zero if the plist could not be written.
_ckipper_desktop_bundle_write_plist() {
    local bundle="$1" name="$2" icon_copied="$3"
    local display="Claude-$(_ckipper_desktop_bundle_title_case "$name")"
    local icon_block=""
    [[ "$icon_copied" = "true" ]] && \
        icon_block=$'    <key>CFBundleIconFile</key>\n    <string>AppIcon</string>\n'
    _ckipper_desktop_bundle_plist_body "$name" "$display" "$icon_block" \
        > "$bundle/Contents/Info.plist"
}

# Emit the Info.plist body to stdout. Split out of _write_plist so the
# writer stays under the 25-line cap (plists are inherently verbose).
#
# Args:
#   $1 — canonical lowercase name (for CFBundleIdentifier suffix)
#   $2 — display name (for CFBundleName)
#   $3 — pre-formatted icon block (empty when no icon was copied)
#
# Returns: 0 always. Prints the plist XML to stdout.
_ckipper_desktop_bundle_plist_body() {
    local name="$1" display="$2" icon_block="$3"
    cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>launcher</string>
    <key>CFBundleIdentifier</key>
    <string>${_CKIPPER_DESKTOP_BUNDLE_ID_PREFIX}.${name}</string>
    <key>CFBundleName</key>
    <string>${display}</string>
    <key>CFBundleShortVersionString</key>
    <string>1.0</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>NSHighResolutionCapable</key>
    <true/>
${icon_block}</dict>
</plist>
EOF
}

# Best-effort copy the system Claude.app's icon into the new bundle.
#
# Reads _CKIPPER_TEST_CLAUDE_APP at call time so tests can stub the source.
# Returns 0 only when the icon was successfully copied (the caller uses this
# to decide whether to include CFBundleIconFile in the plist).
#
# Args: $1 — bundle path.
# Returns: 0 on copy success; non-zero if the source icon is missing or copy
#          failed (the caller treats this as "no icon" and continues).
_ckipper_desktop_bundle_copy_icon() {
    local bundle="$1"
    local source_app="${_CKIPPER_TEST_CLAUDE_APP:-$_CKIPPER_DESKTOP_SYSTEM_APP}"
    local source_icon="$source_app/Contents/Resources/AppIcon.icns"
    [[ -f "$source_icon" ]] || return 1
    cp "$source_icon" "$bundle/Contents/Resources/AppIcon.icns"
}

# Register the new bundle with Launch Services so macOS picks it up without
# a logout. Best-effort: if lsregister is missing (e.g. in CI containers or
# under _CKIPPER_TEST_LSREGISTER pointing at a nonexistent path), silently
# skip. Always returns 0 so the caller doesn't treat indexing as a hard
# failure.
#
# Args: $1 — bundle path.
# Returns: 0 always.
_ckipper_desktop_bundle_lsregister() {
    local bundle="$1"
    local lsr="${_CKIPPER_TEST_LSREGISTER:-$_CKIPPER_DESKTOP_LSREGISTER_PATH}"
    [[ -x "$lsr" ]] || return 0
    "$lsr" -f "$bundle" >/dev/null 2>&1
    return 0
}
