#!/usr/bin/env zsh
# Alias generation and hook sync subcommands: regenerate_aliases, sync_hooks_for, sync_hooks.

readonly ALIASES_FILE_PERMS=644

# Write a single account's launcher function lines to the aliases file being built.
# Generates a `claude-<name>` function and, if safe, a bare `<name>` shortcut.
#
# Args:
#   $1 — account name
#   $2 — account config directory path
#
# Returns:
#   0 always.
_ckipper_account_generate_account_launcher_function() {
    local account_name="$1" account_dir="$2"
    echo "claude-$account_name() { CLAUDE_CONFIG_DIR=\"$account_dir\" command claude \"\$@\"; }"
    # Bare-name shortcut: also generate `<name>` so users can type the
    # account name directly. Skip if it would shadow a real binary, builtin,
    # alias, or reserved word.
    if _ckipper_account_bare_alias_safe "$account_name"; then
        echo "$account_name() { CLAUDE_CONFIG_DIR=\"$account_dir\" command claude \"\$@\"; }"
    else
        echo "# Bare-name alias '$account_name' skipped (would shadow existing command)."
    fi
}

# Write the bare-claude guard function to stdout.
# Blocks bare `claude` invocations when accounts are registered to prevent
# credential overwrites on the default account's keychain entry.
#
# Returns:
#   0 always.
_ckipper_account_write_bare_claude_guard() {
    echo "claude() {"
    echo "    if [[ -f \"\$_CKIPPER_REGISTRY\" ]] && jq -e '.accounts | length > 0' \"\$_CKIPPER_REGISTRY\" >/dev/null 2>&1; then"
    echo "        local default"
    echo "        default=\$(jq -r '.default // \"\"' \"\$_CKIPPER_REGISTRY\" 2>/dev/null)"
    echo "        echo \"Refusing to launch bare 'claude' — Ckipper has registered accounts.\" >&2"
    echo "        echo \"\" >&2"
    echo "        echo \"Bare 'claude' uses ~/.claude/ and writes to the Keychain entry your\" >&2"
    echo "        echo \"default account ('\${default:-personal}') is registered against. A fresh\" >&2"
    echo "        echo \"/login here would silently overwrite those credentials.\" >&2"
    echo "        echo \"\" >&2"
    echo "        if [[ -n \"\$default\" ]]; then"
    echo "            echo \"Use:  claude-\$default\" >&2"
    echo "        else"
    echo "            echo \"Set a default first: ckipper account default <name>, then use claude-<name>.\" >&2"
    echo "        fi"
    echo "        echo \"\" >&2"
    echo "        echo \"To bypass (fresh login on purpose):  command claude \\\$@\" >&2"
    echo "        return 1"
    echo "    fi"
    echo "    command claude \"\$@\""
    echo "}"
}

# Regenerate ~/.ckipper/aliases.zsh from the current registry and re-source it
# in the calling shell so newly-registered accounts are usable immediately.
#
# Returns:
#   0 always.
_ckipper_account_regenerate_aliases() {
    local out="$CKIPPER_DIR/aliases.zsh"
    local account_name account_dir
    {
        echo "# Auto-generated by ckipper. Do not edit by hand."
        echo "# Self-contained: does not depend on ckipper.zsh or w-function.zsh being sourced."
        echo "# Regenerated whenever an account is added or removed."
        echo ""
        echo "_CKIPPER_REGISTRY=\"\${CKIPPER_DIR:-\$HOME/.ckipper}/accounts.json\""
        echo ""
        _ckipper_account_write_bare_claude_guard
        echo ""
        if [[ -f "$CKIPPER_REGISTRY" ]]; then
            jq -r '.accounts | to_entries[] | "\(.key)\t\(.value.config_dir)"' "$CKIPPER_REGISTRY" | \
                while IFS=$'\t' read -r account_name account_dir; do
                    _ckipper_account_generate_account_launcher_function "$account_name" "$account_dir"
                done
        fi
    } > "$out.tmp"
    # Atomic install — readers in other shells never see a partial file.
    mv "$out.tmp" "$out"
    chmod "$ALIASES_FILE_PERMS" "$out"
    # Re-source in the calling shell so newly-registered accounts are usable
    # immediately without the user having to `exec zsh`.
    source "$out"
}

# Rewrite settings.json hook paths to absolute paths for the given account directory.
# Consumes any prefix matching $HOME/.claude*/hooks/ or $HOME/.ckipper/hooks/.
#
# Args:
#   $1 — account config directory path
#
# Returns:
#   0 always.
_ckipper_account_rewrite_settings_json_hooks() {
    local dir="$1"
    [[ -f "$dir/settings.json" ]] || return 0
    command -v jq &>/dev/null || return 0
    local settings_tmpfile; settings_tmpfile=$(mktemp "$dir/.settings.tmp.XXXXXX")
    jq --arg d "$dir" '
        (.hooks // {}) as $h |
        .hooks = ($h | walk(
            if type == "string" and test("\\$HOME/(\\.claude(-[a-z0-9_-]+)?|\\.ckipper)/hooks/")
            then sub("\\$HOME/(\\.claude(-[a-z0-9_-]+)?|\\.ckipper)/hooks/"; "\($d)/hooks/")
            else . end
        ))
    ' "$dir/settings.json" > "$settings_tmpfile" && mv "$settings_tmpfile" "$dir/settings.json"
}

# Copy hook scripts into an account directory and rewrite settings.json hook paths.
# Allows callers (e.g. _ckipper_account_add) to pass the dir directly before the account
# is registered in the registry.
#
# Args:
#   $1 — account name
#   $2 — (optional) account config directory; looked up in registry if omitted
#
# Returns:
#   0 on success; 1 if directory cannot be resolved.
_ckipper_account_sync_hooks_for() {
    local name="$1" dir="${2:-}"
    if [[ -z "$dir" ]]; then
        _core_registry_check_version || return 1
        dir=$(jq -r --arg n "$name" '.accounts[$n].config_dir' "$CKIPPER_REGISTRY")
        [[ -z "$dir" || "$dir" == "null" ]] && return 1
    fi
    mkdir -p "$dir/hooks"
    cp -a "$CKIPPER_DIR/hooks/." "$dir/hooks/" 2>/dev/null || true
    _ckipper_account_rewrite_settings_json_hooks "$dir"
}

# Copy hooks into all registered accounts.
#
# Returns:
#   0 on success; 1 if registry version check fails.
_ckipper_account_sync_hooks() {
    if [[ ! -f "$CKIPPER_REGISTRY" ]]; then
        echo "No accounts registered."
        return 0
    fi
    _core_registry_check_version || return 1
    local names; names=$(jq -r '.accounts | keys[]' "$CKIPPER_REGISTRY")
    while IFS= read -r name; do
        echo "Syncing hooks → $name"
        _ckipper_account_sync_hooks_for "$name"
    done <<< "$names"
}
