#!/usr/bin/env zsh
# Alias generation and hook sync subcommands: regenerate_aliases, sync_hooks_for, sync_hooks.

_ckipper_regenerate_aliases() {
    local out="$CKIPPER_DIR/aliases.zsh"
    local _name _dir
    {
        echo "# Auto-generated by ckipper. Do not edit by hand."
        echo "# Self-contained: does not depend on ckipper.zsh or w-function.zsh being sourced."
        echo "# Regenerated whenever an account is added or removed."
        echo ""
        echo "_CKIPPER_REGISTRY=\"\${CKIPPER_DIR:-\$HOME/.ckipper}/accounts.json\""
        echo ""
        # Guard: bare 'claude' would default to ~/.claude/ and write to the unsuffixed
        # 'Claude Code-credentials' Keychain entry — which is the SAME entry the
        # default account uses. A fresh /login here silently overwrites those creds.
        # Block bare 'claude' when accounts are registered; users bypass via 'command claude'.
        echo "claude() {"
        echo "    if [[ -f \"\$_CKIPPER_REGISTRY\" ]] && jq -e '.accounts | length > 0' \"\$_CKIPPER_REGISTRY\" >/dev/null 2>&1; then"
        echo "        local default"
        echo "        default=\$(jq -r '.default // \"\"' \"\$_CKIPPER_REGISTRY\" 2>/dev/null)"
        echo "        echo \"Refusing to launch bare 'claude' — Ckipper has registered accounts.\" >&2"
        echo "        echo \"\" >&2"
        echo "        echo \"Bare 'claude' uses ~/.claude/ and writes to the Keychain entry your\" >&2"
        echo "        echo \"default account ('\${default:-personal}') is registered against. A fresh\" >&2"
        echo "        echo \"/login here would silently overwrite those credentials.\" >&2"
        echo "        echo \"\" >&2"
        echo "        if [[ -n \"\$default\" ]]; then"
        echo "            echo \"Use:  claude-\$default\" >&2"
        echo "        else"
        echo "            echo \"Set a default first: ckipper default <name>, then use claude-<name>.\" >&2"
        echo "        fi"
        echo "        echo \"\" >&2"
        echo "        echo \"To bypass (fresh login on purpose):  command claude \\\$@\" >&2"
        echo "        return 1"
        echo "    fi"
        echo "    command claude \"\$@\""
        echo "}"
        echo ""
        if [[ -f "$CKIPPER_REGISTRY" ]]; then
            jq -r '.accounts | to_entries[] | "\(.key)\t\(.value.config_dir)"' "$CKIPPER_REGISTRY" | \
                while IFS=$'\t' read -r _name _dir; do
                    echo "claude-$_name() { CLAUDE_CONFIG_DIR=\"$_dir\" command claude \"\$@\"; }"
                    # Bare-name shortcut: also generate `<name>` so users can
                    # type the account name directly. Skip if it would shadow
                    # a real binary, builtin, alias, or reserved word.
                    if _ckipper_bare_alias_safe "$_name"; then
                        echo "$_name() { CLAUDE_CONFIG_DIR=\"$_dir\" command claude \"\$@\"; }"
                    else
                        echo "# Bare-name alias '$_name' skipped (would shadow existing command)."
                    fi
                done
        fi
    } > "$out.tmp"
    # Atomic install — readers in other shells never see a partial file.
    mv "$out.tmp" "$out"
    chmod 644 "$out"

    # Re-source in the calling shell so newly-registered accounts are usable
    # immediately without the user having to `exec zsh`. Function definitions
    # from a sourced file are global by default in zsh, so this works even
    # though we're sourcing inside a function.
    source "$out"
}

_ckipper_sync_hooks_for() {
    local name="$1" dir="${2:-}"
    # Allow callers (notably _ckipper_add, which deploys hooks BEFORE the
    # account exists in the registry) to pass the dir directly. Without an
    # explicit dir, look it up in the registry.
    if [[ -z "$dir" ]]; then
        _core_registry_check_version || return 1
        dir=$(jq -r --arg n "$name" '.accounts[$n].config_dir' "$CKIPPER_REGISTRY")
        [[ -z "$dir" || "$dir" == "null" ]] && return 1
    fi
    mkdir -p "$dir/hooks"
    cp -a "$CKIPPER_DIR/hooks/." "$dir/hooks/" 2>/dev/null || true

    # Rewrite settings.json hook paths to absolute paths under this account dir.
    # Consumes the entire prefix (`$HOME/.claude/`, `$HOME/.claude-<name>/`, or `$HOME/.ckipper/`)
    # plus `hooks/` so we don't end up with `$HOME<dir>/hooks/...` after substitution.
    if [[ -f "$dir/settings.json" ]] && command -v jq &>/dev/null; then
        local tmp; tmp=$(mktemp "$dir/.settings.tmp.XXXXXX")
        jq --arg d "$dir" '
            (.hooks // {}) as $h |
            .hooks = ($h | walk(
                if type == "string" and test("\\$HOME/(\\.claude(-[a-z0-9_-]+)?|\\.ckipper)/hooks/")
                then sub("\\$HOME/(\\.claude(-[a-z0-9_-]+)?|\\.ckipper)/hooks/"; "\($d)/hooks/")
                else . end
            ))
        ' "$dir/settings.json" > "$tmp" && mv "$tmp" "$dir/settings.json"
    fi
}

_ckipper_sync_hooks() {
    if [[ ! -f "$CKIPPER_REGISTRY" ]]; then
        echo "No accounts registered."
        return 0
    fi
    _core_registry_check_version || return 1
    local names; names=$(jq -r '.accounts | keys[]' "$CKIPPER_REGISTRY")
    while IFS= read -r name; do
        echo "Syncing hooks → $name"
        _ckipper_sync_hooks_for "$name"
    done <<< "$names"
}
